name = "LoopVectorizationTools"
uuid = "e634aa9b-3dae-4dfa-b5f1-f3b4b82f5ae1"
authors = ["Felix Horger <felix.horger@kcl.ac.uk>"]
version = "0.1.0"

[deps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
